cmake_minimum_required(VERSION 3.8)
project(transport_bench)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(std_msgs REQUIRED)
foreach(t pub sub)
  add_executable(${t} ${t}.cpp)
  ament_target_dependencies(${t} rclcpp sensor_msgs std_msgs)
  install(TARGETS ${t} DESTINATION lib/${PROJECT_NAME})
endforeach()
ament_package()
